import type { Transformation } from '../types'

export const TRANSFORMATIONS: Transformation[] = [
  // Moved custom prompt to the top and enabled multi-image
  {
    key: 'customPrompt',
    titleKey: 'transformations.effects.customPrompt.title',
    prompt: 'CUSTOM',
    emoji: '✍️',
    descriptionKey: 'transformations.effects.customPrompt.description',
    isMultiImage: true,
    isSecondaryOptional: true,
    primaryUploaderTitle: 'transformations.effects.customPrompt.uploader1Title',
    primaryUploaderDescription: 'transformations.effects.customPrompt.uploader1Desc',
    secondaryUploaderTitle: 'transformations.effects.customPrompt.uploader2Title',
    secondaryUploaderDescription: 'transformations.effects.customPrompt.uploader2Desc',
  },
  {
    key: 'glmImage',
    titleKey: 'transformations.effects.glmImage.title',
    prompt:
      '竖版手工剪贴簿风格的图像。顶部是一条亮红色粗糙撕裂边缘的纸质横幅，用半透明和纸胶带斜着固定，左上角夹着金色回形针，压着一小块写有「首发」的碎纸。横幅上用粗黑体手工剪报风写着主标题「GLM-Image 开源：国产芯片炼出图像生成 SOTA」，标题周围用黑色马克笔画着放射线和手绘画笔调色盘图标。 背景是拼贴的AI生成图片碎片、芯片电路图纹理、水彩晕染和浅蓝色卡纸。左侧有一个带磨损金属边的数码相框，用透明胶带斜贴，相框内大字写着「自回归 + 扩散解码器」，副标题「9B 自回归理解指令 + 7B DiT 精绘细节」，背景是文字prompt气泡到精美图像的箭头连接图，边缘有手绘箭头标注「读懂指令」「写对文字」。 右侧散落三张不同颜色的撕裂纸条便利贴，被和纸胶带交叉固定。配有芯片实物照片剪影加华为logo小贴纸、中文艺术字海报截图、多分辨率图像网格等插图。三个撕裂纸条标签带粗黑描边：「昇腾 A2 + 昇思 MindSpore：全程国产训练」「CVTG-2K & LongText-Bench：文字渲染开源第一」「384×384 到 2048×2048：任意比例原生支持」。旁边还有一条窄蓝色撕裂纸条写着「认知型生成：知识 + 推理新范式」，上面有马克笔波浪线和星星。 底部是一整条深蓝色撕裂纸带，印着电路纹理，用和纸胶带固定。通栏大标题「从”画个图”到”懂你想要什么”的认知型生成引擎」',
    emoji: '🎨',
    descriptionKey: 'transformations.effects.glmImage.description',
    isTextToImage: true,
    model: 'glm-image',
    exampleImage: '/examples/glmImage.jpg',
  },
  // Viral & Fun (Flattened)
  {
    key: 'figurine',
    titleKey: 'transformations.effects.figurine.title',
    prompt:
      "turn this photo into a character figure. Behind it, place a box with the character's image printed on it, and a computer showing the Blender modeling process on its screen. In front of the box, add a round plastic base with the character figure standing on it. set the scene indoors if possible",
    emoji: '🧍',
    descriptionKey: 'transformations.effects.figurine.description',
    exampleImage: '/examples/figurine.jpg',
  },
  {
    key: 'funko',
    titleKey: 'transformations.effects.funko.title',
    prompt: 'Transform the person into a Funko Pop figure, shown inside and next to its packaging.',
    emoji: '📦',
    descriptionKey: 'transformations.effects.funko.description',
    exampleImage: '/examples/funko.jpg',
  },
  {
    key: 'lego',
    titleKey: 'transformations.effects.lego.title',
    prompt: 'Transform the person into a LEGO minifigure, inside its packaging box.',
    emoji: '🧱',
    descriptionKey: 'transformations.effects.lego.description',
    exampleImage: '/examples/lego.jpg',
  },
  {
    key: 'crochet',
    titleKey: 'transformations.effects.crochet.title',
    prompt:
      'Transform the subject into a handmade crocheted yarn doll with a cute, chibi-style appearance.',
    emoji: '🧶',
    descriptionKey: 'transformations.effects.crochet.description',
    exampleImage: '/examples/crochet.jpg',
  },
  {
    key: 'cosplay',
    titleKey: 'transformations.effects.cosplay.title',
    prompt:
      'Generate a highly detailed, realistic photo of a person cosplaying the character in this illustration. Replicate the pose, expression, and framing.',
    emoji: '🎭',
    descriptionKey: 'transformations.effects.cosplay.description',
    exampleImage: '/examples/cosplay.jpg',
  },
  {
    key: 'plushie',
    titleKey: 'transformations.effects.plushie.title',
    prompt: 'Turn the person in this photo into a cute, soft plushie doll.',
    emoji: '🧸',
    descriptionKey: 'transformations.effects.plushie.description',
    exampleImage: '/examples/plushie.jpg',
  },
  {
    key: 'keychain',
    titleKey: 'transformations.effects.keychain.title',
    prompt: 'Turn the subject into a cute acrylic keychain, shown attached to a bag.',
    emoji: '🔑',
    descriptionKey: 'transformations.effects.keychain.description',
  },

  // Photo & Pro Edits (Flattened)
  {
    key: 'hdEnhance',
    titleKey: 'transformations.effects.hdEnhance.title',
    prompt: 'Enhance this image to high resolution, improving sharpness and clarity.',
    emoji: '🔍',
    descriptionKey: 'transformations.effects.hdEnhance.description',
    exampleImage: '/examples/hdEnhance.jpg',
  },
  {
    key: 'pose',
    titleKey: 'transformations.effects.pose.title',
    prompt:
      'Apply the pose from the second image to the character in the first image. Render as a professional studio photograph.',
    emoji: '💃',
    descriptionKey: 'transformations.effects.pose.description',
    isMultiImage: true,
    primaryUploaderTitle: 'transformations.effects.pose.uploader1Title',
    primaryUploaderDescription: 'transformations.effects.pose.uploader1Desc',
    secondaryUploaderTitle: 'transformations.effects.pose.uploader2Title',
    secondaryUploaderDescription: 'transformations.effects.pose.uploader2Desc',
  },
  {
    key: 'photorealistic',
    titleKey: 'transformations.effects.photorealistic.title',
    prompt: 'Turn this illustration into a photorealistic version.',
    emoji: '🪄',
    descriptionKey: 'transformations.effects.photorealistic.description',
  },
  {
    key: 'fashion',
    titleKey: 'transformations.effects.fashion.title',
    prompt:
      'Transform the photo into a stylized, ultra-realistic fashion magazine portrait with cinematic lighting.',
    emoji: '📸',
    descriptionKey: 'transformations.effects.fashion.description',
    exampleImage: '/examples/fashion.jpg',
  },
  {
    key: 'hyperrealistic',
    titleKey: 'transformations.effects.hyperrealistic.title',
    prompt:
      'Generate a hyper-realistic, fashion-style photo with strong, direct flash lighting, grainy texture, and a cool, confident pose.',
    emoji: '✨',
    descriptionKey: 'transformations.effects.hyperrealistic.description',
    exampleImage: '/examples/hyperrealistic.jpg',
  },

  // Design & Product (Flattened)
  {
    key: 'architecture',
    titleKey: 'transformations.effects.architecture.title',
    prompt:
      'Convert this photo of a building into a miniature architecture model, placed on a cardstock in an indoor setting. Show a computer with modeling software in the background.',
    emoji: '🏗️',
    descriptionKey: 'transformations.effects.architecture.description',
    exampleImage: '/examples/architecture.jpg',
  },
  {
    key: 'productRender',
    titleKey: 'transformations.effects.productRender.title',
    prompt: 'Turn this product sketch into a photorealistic 3D render with studio lighting.',
    emoji: '💡',
    descriptionKey: 'transformations.effects.productRender.description',
  },
  {
    key: 'sodaCan',
    titleKey: 'transformations.effects.sodaCan.title',
    prompt:
      'Design a soda can using this image as the main graphic, and show it in a professional product shot.',
    emoji: '🥤',
    descriptionKey: 'transformations.effects.sodaCan.description',
  },
  {
    key: 'industrialDesign',
    titleKey: 'transformations.effects.industrialDesign.title',
    prompt:
      'Turn this industrial design sketch into a realistic product photo, rendered with light brown leather and displayed in a minimalist museum setting.',
    emoji: '🛋️',
    descriptionKey: 'transformations.effects.industrialDesign.description',
  },
  {
    key: 'iphoneWallpaper',
    titleKey: 'transformations.effects.iphoneWallpaper.title',
    prompt:
      "Turn the image into an iPhone lock screen wallpaper effect, with the phone's time (01:16), date (Sunday, September 16), and status bar information (battery, signal, etc.), with the flashlight and camera buttons at the bottom, overlaid on the image. The original image should be adapted to a vertical composition that fits a phone screen. The phone is placed on a solid color background of the same color scheme.",
    emoji: '📱',
    descriptionKey: 'transformations.effects.iphoneWallpaper.description',
  },

  // Creative Tools (Flattened)
  {
    key: 'colorPalette',
    titleKey: 'transformations.effects.colorPalette.title',
    prompt: 'Turn this image into a clean, hand-drawn line art sketch.', // Step 1 prompt
    stepTwoPrompt: 'Color the line art using the colors from the second image.', // Step 2 prompt
    emoji: '🎨',
    descriptionKey: 'transformations.effects.colorPalette.description',
    isMultiImage: true,
    isTwoStep: true,
    primaryUploaderTitle: 'transformations.effects.colorPalette.uploader1Title',
    primaryUploaderDescription: 'transformations.effects.colorPalette.uploader1Desc',
    secondaryUploaderTitle: 'transformations.effects.colorPalette.uploader2Title',
    secondaryUploaderDescription: 'transformations.effects.colorPalette.uploader2Desc',
    exampleImage: '/examples/colorPalette.jpg',
  },
  {
    key: 'videoGeneration',
    titleKey: 'transformations.video.title',
    emoji: '🎬',
    descriptionKey: 'transformations.video.description',
    isVideo: true,
    prompt: 'CUSTOM',
  },
  {
    key: 'isolate',
    titleKey: 'transformations.effects.isolate.title',
    prompt:
      'Isolate the person in the masked area and generate a high-definition photo of them against a neutral background.',
    emoji: '🎯',
    descriptionKey: 'transformations.effects.isolate.description',
  },
  {
    key: 'screen3d',
    titleKey: 'transformations.effects.screen3d.title',
    prompt:
      'For an image with a screen, add content that appears to be glasses-free 3D, popping out of the screen.',
    emoji: '📺',
    descriptionKey: 'transformations.effects.screen3d.description',
  },
  {
    key: 'makeup',
    titleKey: 'transformations.effects.makeup.title',
    prompt: 'Analyze the makeup in this photo and suggest improvements by drawing with a red pen.',
    emoji: '💄',
    descriptionKey: 'transformations.effects.makeup.description',
  },
  {
    key: 'background',
    titleKey: 'transformations.effects.background.title',
    prompt: 'Change the background to a Y2K aesthetic style.',
    emoji: '🪩',
    descriptionKey: 'transformations.effects.background.description',
  },
  {
    key: 'addIllustration',
    titleKey: 'transformations.effects.addIllustration.title',
    prompt:
      'Add a cute, cartoon-style illustrated couple into the real-world scene, sitting and talking.',
    emoji: '🧑‍🎨',
    descriptionKey: 'transformations.effects.addIllustration.description',
  },

  // Category: 50+ Artistic Effects
  {
    key: 'category_effects',
    titleKey: 'transformations.categories.effects.title',
    emoji: '✨',
    items: [
      {
        key: 'pixelArt',
        titleKey: 'transformations.effects.pixelArt.title',
        prompt: 'Redraw the image in a retro 8-bit pixel art style.',
        emoji: '👾',
        descriptionKey: 'transformations.effects.pixelArt.description',
      },
      {
        key: 'watercolor',
        titleKey: 'transformations.effects.watercolor.title',
        prompt: 'Transform the image into a soft and vibrant watercolor painting.',
        emoji: '🖌️',
        descriptionKey: 'transformations.effects.watercolor.description',
      },
      {
        key: 'popArt',
        titleKey: 'transformations.effects.popArt.title',
        prompt:
          "Reimagine the image in the style of Andy Warhol's pop art, with bold colors and screen-print effects.",
        emoji: '🎨',
        descriptionKey: 'transformations.effects.popArt.description',
      },
      {
        key: 'comicBook',
        titleKey: 'transformations.effects.comicBook.title',
        prompt:
          'Convert the image into a classic comic book panel with halftones, bold outlines, and action text.',
        emoji: '💥',
        descriptionKey: 'transformations.effects.comicBook.description',
      },
      {
        key: 'claymation',
        titleKey: 'transformations.effects.claymation.title',
        prompt: 'Recreate the image as a charming stop-motion claymation scene.',
        emoji: '🗿',
        descriptionKey: 'transformations.effects.claymation.description',
      },
      {
        key: 'ukiyoE',
        titleKey: 'transformations.effects.ukiyoE.title',
        prompt: 'Redraw the image in the style of a traditional Japanese Ukiyo-e woodblock print.',
        emoji: '🌊',
        descriptionKey: 'transformations.effects.ukiyoE.description',
      },
      {
        key: 'stainedGlass',
        titleKey: 'transformations.effects.stainedGlass.title',
        prompt: 'Transform the image into a vibrant stained glass window with dark lead lines.',
        emoji: '🪟',
        descriptionKey: 'transformations.effects.stainedGlass.description',
      },
      {
        key: 'origami',
        titleKey: 'transformations.effects.origami.title',
        prompt: 'Reconstruct the subject of the image using folded paper in an origami style.',
        emoji: '🦢',
        descriptionKey: 'transformations.effects.origami.description',
      },
      {
        key: 'neonGlow',
        titleKey: 'transformations.effects.neonGlow.title',
        prompt: 'Outline the subject in bright, glowing neon lights against a dark background.',
        emoji: '💡',
        descriptionKey: 'transformations.effects.neonGlow.description',
      },
      {
        key: 'doodleArt',
        titleKey: 'transformations.effects.doodleArt.title',
        prompt: 'Overlay the image with playful, hand-drawn doodle-style illustrations.',
        emoji: '✏️',
        descriptionKey: 'transformations.effects.doodleArt.description',
      },
      {
        key: 'vintagePhoto',
        titleKey: 'transformations.effects.vintagePhoto.title',
        prompt:
          'Give the image an aged, sepia-toned vintage photograph look from the early 20th century.',
        emoji: '📜',
        descriptionKey: 'transformations.effects.vintagePhoto.description',
      },
      {
        key: 'blueprintSketch',
        titleKey: 'transformations.effects.blueprintSketch.title',
        prompt: 'Convert the image into a technical blueprint-style architectural drawing.',
        emoji: '📐',
        descriptionKey: 'transformations.effects.blueprintSketch.description',
      },
      {
        key: 'glitchArt',
        titleKey: 'transformations.effects.glitchArt.title',
        prompt: 'Apply a digital glitch effect with datamoshing, pixel sorting, and RGB shifts.',
        emoji: '📉',
        descriptionKey: 'transformations.effects.glitchArt.description',
      },
      {
        key: 'doubleExposure',
        titleKey: 'transformations.effects.doubleExposure.title',
        prompt:
          'Create a double exposure effect, blending the image with a nature scene like a forest or a mountain range.',
        emoji: '🏞️',
        descriptionKey: 'transformations.effects.doubleExposure.description',
      },
      {
        key: 'hologram',
        titleKey: 'transformations.effects.hologram.title',
        prompt: 'Project the subject as a futuristic, glowing blue hologram.',
        emoji: '🌐',
        descriptionKey: 'transformations.effects.hologram.description',
      },
      {
        key: 'lowPoly',
        titleKey: 'transformations.effects.lowPoly.title',
        prompt: 'Reconstruct the image using a low-polygon geometric mesh.',
        emoji: '🔺',
        descriptionKey: 'transformations.effects.lowPoly.description',
      },
      {
        key: 'charcoalSketch',
        titleKey: 'transformations.effects.charcoalSketch.title',
        prompt: 'Redraw the image as a dramatic, high-contrast charcoal sketch on textured paper.',
        emoji: '✍🏽',
        descriptionKey: 'transformations.effects.charcoalSketch.description',
      },
      {
        key: 'impressionism',
        titleKey: 'transformations.effects.impressionism.title',
        prompt:
          'Repaint the image in the style of an Impressionist masterpiece, with visible brushstrokes and a focus on light.',
        emoji: '👨‍🎨',
        descriptionKey: 'transformations.effects.impressionism.description',
      },
      {
        key: 'cubism',
        titleKey: 'transformations.effects.cubism.title',
        prompt:
          'Deconstruct and reassemble the subject in the abstract, geometric style of Cubism.',
        emoji: '🧊',
        descriptionKey: 'transformations.effects.cubism.description',
      },
      {
        key: 'steampunk',
        titleKey: 'transformations.effects.steampunk.title',
        prompt:
          'Reimagine the subject with steampunk aesthetics, featuring gears, brass, and Victorian-era technology.',
        emoji: '⚙️',
        descriptionKey: 'transformations.effects.steampunk.description',
      },
      {
        key: 'fantasyArt',
        titleKey: 'transformations.effects.fantasyArt.title',
        prompt:
          'Transform the image into an epic fantasy-style painting, with magical elements and dramatic lighting.',
        emoji: '🐉',
        descriptionKey: 'transformations.effects.fantasyArt.description',
      },
      {
        key: 'graffiti',
        titleKey: 'transformations.effects.graffiti.title',
        prompt: 'Spray-paint the image as vibrant graffiti on a brick wall.',
        emoji: '🎨',
        descriptionKey: 'transformations.effects.graffiti.description',
      },
      {
        key: 'minimalistLineArt',
        titleKey: 'transformations.effects.minimalistLineArt.title',
        prompt: 'Reduce the image to a single, continuous, minimalist line drawing.',
        emoji: '〰️',
        descriptionKey: 'transformations.effects.minimalistLineArt.description',
      },
      {
        key: 'storybook',
        titleKey: 'transformations.effects.storybook.title',
        prompt: "Redraw the image in the style of a whimsical children's storybook illustration.",
        emoji: '📖',
        descriptionKey: 'transformations.effects.storybook.description',
      },
      {
        key: 'thermal',
        titleKey: 'transformations.effects.thermal.title',
        prompt: 'Apply a thermal imaging effect with a heat map color palette.',
        emoji: '🌡️',
        descriptionKey: 'transformations.effects.thermal.description',
      },
      {
        key: 'risograph',
        titleKey: 'transformations.effects.risograph.title',
        prompt:
          'Simulate a risograph print effect with grainy textures and limited, overlapping color layers.',
        emoji: '📠',
        descriptionKey: 'transformations.effects.risograph.description',
      },
      {
        key: 'crossStitch',
        titleKey: 'transformations.effects.crossStitch.title',
        prompt: 'Convert the image into a textured, handmade cross-stitch pattern.',
        emoji: '🧵',
        descriptionKey: 'transformations.effects.crossStitch.description',
      },
      {
        key: 'tattoo',
        titleKey: 'transformations.effects.tattoo.title',
        prompt: 'Redesign the subject as a classic American traditional style tattoo.',
        emoji: '🖋️',
        descriptionKey: 'transformations.effects.tattoo.description',
      },
      {
        key: 'psychedelic',
        titleKey: 'transformations.effects.psychedelic.title',
        prompt: 'Apply a vibrant, swirling, psychedelic art style from the 1960s.',
        emoji: '🌀',
        descriptionKey: 'transformations.effects.psychedelic.description',
      },
      {
        key: 'gothic',
        titleKey: 'transformations.effects.gothic.title',
        prompt:
          'Reimagine the scene with a dark, gothic art style, featuring dramatic shadows and architecture.',
        emoji: '🏰',
        descriptionKey: 'transformations.effects.gothic.description',
      },
      {
        key: 'tribal',
        titleKey: 'transformations.effects.tribal.title',
        prompt: 'Redraw the subject using patterns and motifs from traditional tribal art.',
        emoji: '🗿',
        descriptionKey: 'transformations.effects.tribal.description',
      },
      {
        key: 'dotPainting',
        titleKey: 'transformations.effects.dotPainting.title',
        prompt: 'Recreate the image using the dot painting technique of Aboriginal art.',
        emoji: '🎨',
        descriptionKey: 'transformations.effects.dotPainting.description',
      },
      {
        key: 'chalk',
        titleKey: 'transformations.effects.chalk.title',
        prompt: 'Draw the image as a colorful chalk illustration on a sidewalk.',
        emoji: '🖍️',
        descriptionKey: 'transformations.effects.chalk.description',
      },
      {
        key: 'sandArt',
        titleKey: 'transformations.effects.sandArt.title',
        prompt: 'Recreate the image as if it were made from colored sand.',
        emoji: '🏜️',
        descriptionKey: 'transformations.effects.sandArt.description',
      },
      {
        key: 'mosaic',
        titleKey: 'transformations.effects.mosaic.title',
        prompt: 'Transform the image into a mosaic made of small ceramic tiles.',
        emoji: '💠',
        descriptionKey: 'transformations.effects.mosaic.description',
      },
      {
        key: 'paperQuilling',
        titleKey: 'transformations.effects.paperQuilling.title',
        prompt:
          'Reconstruct the subject using the art of paper quilling, with rolled and shaped strips of paper.',
        emoji: '📜',
        descriptionKey: 'transformations.effects.paperQuilling.description',
      },
      {
        key: 'woodCarving',
        titleKey: 'transformations.effects.woodCarving.title',
        prompt: 'Recreate the subject as a detailed wood carving.',
        emoji: '🪵',
        descriptionKey: 'transformations.effects.woodCarving.description',
      },
      {
        key: 'iceSculpture',
        titleKey: 'transformations.effects.iceSculpture.title',
        prompt: 'Transform the subject into a translucent, detailed ice sculpture.',
        emoji: '🧊',
        descriptionKey: 'transformations.effects.iceSculpture.description',
      },
      {
        key: 'bronzeStatue',
        titleKey: 'transformations.effects.bronzeStatue.title',
        prompt: 'Turn the subject into a weathered bronze statue on a pedestal.',
        emoji: '🗿',
        descriptionKey: 'transformations.effects.bronzeStatue.description',
      },
      {
        key: 'galaxy',
        titleKey: 'transformations.effects.galaxy.title',
        prompt: 'Blend the image with a vibrant nebula and starry galaxy background.',
        emoji: '🌌',
        descriptionKey: 'transformations.effects.galaxy.description',
      },
      {
        key: 'fire',
        titleKey: 'transformations.effects.fire.title',
        prompt: 'Reimagine the subject as if it were formed from roaring flames.',
        emoji: '🔥',
        descriptionKey: 'transformations.effects.fire.description',
      },
      {
        key: 'water',
        titleKey: 'transformations.effects.water.title',
        prompt: 'Reimagine the subject as if it were formed from flowing, liquid water.',
        emoji: '💧',
        descriptionKey: 'transformations.effects.water.description',
      },
      {
        key: 'smokeArt',
        titleKey: 'transformations.effects.smokeArt.title',
        prompt: 'Create the subject from elegant, swirling wisps of smoke.',
        emoji: '💨',
        descriptionKey: 'transformations.effects.smokeArt.description',
      },
      {
        key: 'vectorArt',
        titleKey: 'transformations.effects.vectorArt.title',
        prompt:
          'Convert the photo into clean, scalable vector art with flat colors and sharp lines.',
        emoji: '🎨',
        descriptionKey: 'transformations.effects.vectorArt.description',
      },
      {
        key: 'infrared',
        titleKey: 'transformations.effects.infrared.title',
        prompt: 'Simulate an infrared photo effect with surreal colors and glowing foliage.',
        emoji: '📸',
        descriptionKey: 'transformations.effects.infrared.description',
      },
      {
        key: 'knitted',
        titleKey: 'transformations.effects.knitted.title',
        prompt: 'Recreate the image as a cozy, knitted wool pattern.',
        emoji: '🧶',
        descriptionKey: 'transformations.effects.knitted.description',
      },
      {
        key: 'etching',
        titleKey: 'transformations.effects.etching.title',
        prompt: 'Redraw the image as a classic black and white etching or engraving.',
        emoji: '✒️',
        descriptionKey: 'transformations.effects.etching.description',
      },
      {
        key: 'diorama',
        titleKey: 'transformations.effects.diorama.title',
        prompt: 'Turn the scene into a miniature 3D diorama inside a box.',
        emoji: '📦',
        descriptionKey: 'transformations.effects.diorama.description',
      },
      {
        key: 'cyberpunk',
        titleKey: 'transformations.effects.cyberpunk.title',
        prompt: 'Transform the scene into a futuristic cyberpunk city.',
        emoji: '🤖',
        descriptionKey: 'transformations.effects.cyberpunk.description',
      },
      {
        key: 'vanGogh',
        titleKey: 'transformations.effects.vanGogh.title',
        prompt: "Reimagine the photo in the style of Van Gogh's 'Starry Night'.",
        emoji: '🌌',
        descriptionKey: 'transformations.effects.vanGogh.description',
      },
      {
        key: 'lineArt',
        titleKey: 'transformations.effects.lineArt.title',
        prompt: 'Turn the image into a clean, hand-drawn line art sketch.',
        emoji: '✍🏻',
        descriptionKey: 'transformations.effects.lineArt.description',
      },
      {
        key: 'paintingProcess',
        titleKey: 'transformations.effects.paintingProcess.title',
        prompt:
          'Generate a 4-panel grid showing the artistic process of creating this image, from sketch to final render.',
        emoji: '🖼️',
        descriptionKey: 'transformations.effects.paintingProcess.description',
        exampleImage: '/examples/paintingProcess.jpg',
      },
      {
        key: 'markerSketch',
        titleKey: 'transformations.effects.markerSketch.title',
        prompt: 'Redraw the image in the style of a Copic marker sketch, often used in design.',
        emoji: '🖊️',
        descriptionKey: 'transformations.effects.markerSketch.description',
      },
    ],
  },
]
